import { useRouter } from 'next/router'
import { useContext, useEffect } from 'react'
import Head from 'next/head'
import Layout from '../components/Layout.js'
import UserContext from '../components/UserContext'
import { useSupabaseClient } from '@supabase/auth-helpers-react'

export default function Contact() {
  const { user, logout, loading } = useContext(UserContext)
  const router = useRouter()
  const supabaseClient = useSupabaseClient()
  useEffect(() => {
    if (!(user || loading)) {
      router.push('/login')
    }
  }, [user, loading, router])
  async function signOut(){
    await supabaseClient.auth.signOut()
    router.reload(window.location.pathname)
  }
  return (
    <Layout>
      <Head>
        <title>WebTech - user signedin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { !(user || loading) ?
        <p className="text-lg text-center text-gray-500">Redirecting...</p>
        :
        <div className="flex flex-col items-center justify-center min-h-screen py-2">
          <button
            className="px-4 py-2 mb-4 text-lg text-white bg-blue-500 rounded hover:bg-blue-700"
            onClick={signOut}
          >
            Logout
          </button>
          <div className="p-4 text-sm bg-gray-100 rounded-md">
            <p><strong>Email:</strong> {user.email}</p>
          </div>
        </div>
      }
    </Layout>
  )
}
